apps_url_dict = {
    0: ("ART_AND_DESIGN","https://play.google.com/store/apps/collection/cluster?clp=ogoaCAESDkFSVF9BTkRfREVTSUdOKgIIB1ICCAE%3D:S:ANO1ljJy3eQ&gsr=Ch2iChoIARIOQVJUX0FORF9ERVNJR04qAggHUgIIAQ%3D%3D:S:ANO1ljIR5CU"),
    1: ("BEAUTY","https://play.google.com/store/apps/collection/cluster?clp=ogoSCAESBkJFQVVUWSoCCAdSAggB:S:ANO1ljJ0zQY&gsr=ChWiChIIARIGQkVBVVRZKgIIB1ICCAE%3D:S:ANO1ljK2uX4"),
    2: ("LIBRARIES_AND_DEMO","https://play.google.com/store/apps/collection/cluster?clp=ogoeCAESEkxJQlJBUklFU19BTkRfREVNTyoCCAdSAggB:S:ANO1ljKEkyU&gsr=CiGiCh4IARISTElCUkFSSUVTX0FORF9ERU1PKgIIB1ICCAE%3D:S:ANO1ljKdVUQ"),
    3: ("HOUSE_AND_HOME","https://play.google.com/store/apps/collection/cluster?clp=ogoaCAESDkhPVVNFX0FORF9IT01FKgIIB1ICCAE%3D:S:ANO1ljI61gs&gsr=Ch2iChoIARIOSE9VU0VfQU5EX0hPTUUqAggHUgIIAQ%3D%3D:S:ANO1ljJ-4CI"),
    4: ("WEATHER","https://play.google.com/store/apps/collection/cluster?clp=ogoTCAESB1dFQVRIRVIqAggHUgIIAQ%3D%3D:S:ANO1ljJk68Q&gsr=ChaiChMIARIHV0VBVEhFUioCCAdSAggB:S:ANO1ljIAgY4"),
    5: ("FOOD_AND_DRINK","https://play.google.com/store/apps/collection/cluster?clp=ogoaCAESDkZPT0RfQU5EX0RSSU5LKgIIB1ICCAE%3D:S:ANO1ljKFOlk&gsr=Ch2iChoIARIORk9PRF9BTkRfRFJJTksqAggHUgIIAQ%3D%3D:S:ANO1ljLWIvc"),
    6: ("SHOPPING","https://play.google.com/store/apps/collection/cluster?clp=ogoUCAESCFNIT1BQSU5HKgIIB1ICCAE%3D:S:ANO1ljJTu6Y&gsr=CheiChQIARIIU0hPUFBJTkcqAggHUgIIAQ%3D%3D:S:ANO1ljLufhY"),
    7: ("COMMUNICATION", "https://play.google.com/store/apps/collection/cluster?clp=ogoZCAESDUNPTU1VTklDQVRJT04qAggHUgIIAQ%3D%3D:S:ANO1ljKqHe4&gsr=ChyiChkIARINQ09NTVVOSUNBVElPTioCCAdSAggB:S:ANO1ljIpBzo"),
    8: ("BUSINESS", "https://play.google.com/store/apps/collection/cluster?clp=ogoUCAESCEJVU0lORVNTKgIIB1ICCAE%3D:S:ANO1ljL-OFs&gsr=CheiChQIARIIQlVTSU5FU1MqAggHUgIIAQ%3D%3D:S:ANO1ljKPhFI"),
    9: ("PARENTING", "https://play.google.com/store/apps/collection/cluster?clp=ogoVCAESCVBBUkVOVElORyoCCAdSAggB:S:ANO1ljKni9M&gsr=ChiiChUIARIJUEFSRU5USU5HKgIIB1ICCAE%3D:S:ANO1ljJzQHA"),
    10: ("EDUCATION", "https://play.google.com/store/apps/collection/cluster?clp=ogoVCAESCUVEVUNBVElPTioCCAdSAggB:S:ANO1ljJexIQ&gsr=ChiiChUIARIJRURVQ0FUSU9OKgIIB1ICCAE%3D:S:ANO1ljKyA18"),
    11: ("DATING", "https://play.google.com/store/apps/collection/cluster?clp=0g4dChsKFW1vdmVyc19zaGFrZXJzX0RBVElORxAHGAM%3D:S:ANO1ljJZo_A&gsr=CiDSDh0KGwoVbW92ZXJzX3NoYWtlcnNfREFUSU5HEAcYAw%3D%3D:S:ANO1ljLwxJ8"),
    12: ("ENTERTAINMENT","https://play.google.com/store/apps/collection/cluster?clp=ogoZCAESDUVOVEVSVEFJTk1FTlQqAggHUgIIAQ%3D%3D:S:ANO1ljK13fQ&gsr=ChyiChkIARINRU5URVJUQUlOTUVOVCoCCAdSAggB:S:ANO1ljIZ-VM"),
    13: ("SPORTS", "https://play.google.com/store/apps/collection/cluster?clp=ogoSCAESBlNQT1JUUyoCCAdSAggB:S:ANO1ljIsZbI&gsr=ChWiChIIARIGU1BPUlRTKgIIB1ICCAE%3D:S:ANO1ljJ6ABI"),
    14: ("LIFESTYLE", "https://play.google.com/store/apps/collection/cluster?clp=ogoVCAESCUxJRkVTVFlMRSoCCAdSAggB:S:ANO1ljKvSJ4&gsr=ChiiChUIARIJTElGRVNUWUxFKgIIB1ICCAE%3D:S:ANO1ljJ4w4I"),
    15: ("EVENTS", "https://play.google.com/store/apps/collection/cluster?clp=ogoSCAESBkVWRU5UUyoCCAdSAggB:S:ANO1ljKHiHU&gsr=ChWiChIIARIGRVZFTlRTKgIIB1ICCAE%3D:S:ANO1ljJWH00"),
    16: ("TOOLS", "https://play.google.com/store/apps/collection/cluster?clp=ogoRCAESBVRPT0xTKgIIB1ICCAE%3D:S:ANO1ljJ5-OA&gsr=ChSiChEIARIFVE9PTFMqAggHUgIIAQ%3D%3D:S:ANO1ljJNkiQ"),
    17: ("FINANCE", "https://play.google.com/store/apps/collection/cluster?clp=ogoTCAESB0ZJTkFOQ0UqAggHUgIIAQ%3D%3D:S:ANO1ljKOn7g&gsr=ChaiChMIARIHRklOQU5DRSoCCAdSAggB:S:ANO1ljLmVzI"),
    18: ("PHOTOGRAPHY", "https://play.google.com/store/apps/collection/cluster?clp=ogoXCAESC1BIT1RPR1JBUEhZKgIIB1ICCAE%3D:S:ANO1ljKwbVQ&gsr=ChqiChcIARILUEhPVE9HUkFQSFkqAggHUgIIAQ%3D%3D:S:ANO1ljLW_Mg"),
    19: ("COMICS", "https://play.google.com/store/apps/collection/cluster?clp=ogoSCAESBkNPTUlDUyoCCAdSAggB:S:ANO1ljJmsPk&gsr=ChWiChIIARIGQ09NSUNTKgIIB1ICCAE%3D:S:ANO1ljKDgII"),
    20: ("BOOKS_AND_REFERENCE", "https://play.google.com/store/apps/collection/cluster?clp=ogofCAESE0JPT0tTX0FORF9SRUZFUkVOQ0UqAggHUgIIAQ%3D%3D:S:ANO1ljKWVq4&gsr=CiKiCh8IARITQk9PS1NfQU5EX1JFRkVSRU5DRSoCCAdSAggB:S:ANO1ljJRBHo"),
    21: ("MAPS_AND_NAVIGATION", "https://play.google.com/store/apps/collection/cluster?clp=ogofCAESE01BUFNfQU5EX05BVklHQVRJT04qAggHUgIIAQ%3D%3D:S:ANO1ljJG6fo&gsr=CiKiCh8IARITTUFQU19BTkRfTkFWSUdBVElPTioCCAdSAggB:S:ANO1ljLFPeQ"),
    22: ("MEDICAL", "https://play.google.com/store/apps/collection/cluster?clp=0g4fCh0KF3RvcHNlbGxpbmdfZnJlZV9NRURJQ0FMEAcYAw%3D%3D:S:ANO1ljKb330&gsr=CiLSDh8KHQoXdG9wc2VsbGluZ19mcmVlX01FRElDQUwQBxgD:S:ANO1ljKyYVU"),
    23: ("MUSIC_AND_AUDIO", "https://play.google.com/store/apps/collection/cluster?clp=ogobCAESD01VU0lDX0FORF9BVURJTyoCCAdSAggB:S:ANO1ljJEFE4&gsr=Ch6iChsIARIPTVVTSUNfQU5EX0FVRElPKgIIB1ICCAE%3D:S:ANO1ljJ7wpw"),
    24: ("NEWS_AND_MAGAZINES", "https://play.google.com/store/apps/collection/cluster?clp=ogoeCAESEk5FV1NfQU5EX01BR0FaSU5FUyoCCAdSAggB:S:ANO1ljJ68zs&gsr=CiGiCh4IARISTkVXU19BTkRfTUFHQVpJTkVTKgIIB1ICCAE%3D:S:ANO1ljLqIXM"),
    25: ("PERSONALIZATION", "https://play.google.com/store/apps/collection/cluster?clp=ogobCAESD1BFUlNPTkFMSVpBVElPTioCCAdSAggB:S:ANO1ljLVBrs&gsr=Ch6iChsIARIPUEVSU09OQUxJWkFUSU9OKgIIB1ICCAE%3D:S:ANO1ljLmM7w"),
    26: ("PRODUCTIVITY", "https://play.google.com/store/apps/collection/cluster?clp=ogoYCAESDFBST0RVQ1RJVklUWSoCCAdSAggB:S:ANO1ljKD9aE&gsr=ChuiChgIARIMUFJPRFVDVElWSVRZKgIIB1ICCAE%3D:S:ANO1ljILYOs"),
    27: ("VIDEO_PLAYERS", "https://play.google.com/store/apps/collection/cluster?clp=ogoZCAESDVZJREVPX1BMQVlFUlMqAggHUgIIAQ%3D%3D:S:ANO1ljI46gw&gsr=ChyiChkIARINVklERU9fUExBWUVSUyoCCAdSAggB:S:ANO1ljJxVoE"),
    28: ("HEALTH_AND_FITNESS", "https://play.google.com/store/apps/collection/cluster?clp=ogoeCAESEkhFQUxUSF9BTkRfRklUTkVTUyoCCAdSAggB:S:ANO1ljLz90Y&gsr=CiGiCh4IARISSEVBTFRIX0FORF9GSVRORVNTKgIIB1ICCAE%3D:S:ANO1ljLIBUo"),
    29: ("SOCIAL", "https://play.google.com/store/apps/collection/cluster?clp=ogoSCAESBlNPQ0lBTCoCCAdSAggB:S:ANO1ljJA8pI&gsr=ChWiChIIARIGU09DSUFMKgIIB1ICCAE%3D:S:ANO1ljIDwks"),
    30: ("TRAVEL_AND_LOCAL", "https://play.google.com/store/apps/collection/cluster?clp=ogocCAESEFRSQVZFTF9BTkRfTE9DQUwqAggHUgIIAQ%3D%3D:S:ANO1ljJlllk&gsr=Ch-iChwIARIQVFJBVkVMX0FORF9MT0NBTCoCCAdSAggB:S:ANO1ljIB4zw"),
    31: ("AUTO_AND_VEHICLES", "https://play.google.com/store/apps/collection/cluster?clp=ogodCAESEUFVVE9fQU5EX1ZFSElDTEVTKgIIB1ICCAE%3D:S:ANO1ljKStL8&gsr=CiCiCh0IARIRQVVUT19BTkRfVkVISUNMRVMqAggHUgIIAQ%3D%3D:S:ANO1ljJ-TRk"),
    32: ("ANDROID_WEAR", "https://play.google.com/store/apps/collection/cluster?clp=0g4kCiIKHHRvcHNlbGxpbmdfZnJlZV9BTkRST0lEX1dFQVIQBxgD:S:ANO1ljIp_Rk&gsr=CifSDiQKIgocdG9wc2VsbGluZ19mcmVlX0FORFJPSURfV0VBUhAHGAM%3D:S:ANO1ljLJKhY")
}